name: MyChunk
main: me.ellbristow.mychunk.MyChunk
version: 2.6
author: dwilson390
description: >
             Buy/Sell chunks for currency, get protection, make profit.
softdepend: [Vault,My Worlds,Multiverse,dynmap,DynmapMyChunk,Factions,Towny]

commands:
  mychunk:
    description: Use /mychunk ? for command help
    aliases: [mc,chunk]
#  gang:
#    description: Use /gang ? for command help
#    aliases: [g]

permissions:

#####################
# Permission Groups #
#####################

# ALL Permissions #
  mychunk.*:
    description: Admin permission for total access
    children:
      mychunk.buy: true
      mychunk.commands.*: true
      mychunk.claim.*: true
      mychunk.free: true
      mychunk.override: true
      mychunk.sell: true
      mychunk.server.*: true
      mychunk.public.*: true
      mychunk.unclaim.*: true
      mychunk.allowmobs: true
      mychunk.allowpvp: true
      mychunk.gang.*: true
      
# ALL Gang Permissions #

  mychunk.gang.*:
    description: Admin access to all Gang permissions
    children:
      mychunk.commands.gang.*: true
      
# ALL Commands #
  mychunk.commands.*:
    description: Access to all MyChunk commands
    children:
      mychunk.commands.claimarea: true
      mychunk.commands.expirydays: true
      mychunk.commands.info.others: true
      mychunk.commands.max: true
      mychunk.commands.obprice: true
      mychunk.commands.price: true
      mychunk.commands.purge.*: true
      mychunk.commands.ramprate: true
      mychunk.commands.refund: true
      mychunk.commands.reload: true
      mychunk.commands.toggle.*: true
      mychunk.commands.unclaimarea: true
      mychunk.commands.user: true
      mychunk.commands.world.*: true
      mychunk.commands.gang.*: true
      mychunk.commands.gangmultiplier: true
      mychunk.commands.gangnamelength: true
      
# ALL Gang Commands #
  mychunk.commands.gang.*:
    desciption: Admin access to all gang commands
    children:
      mychunk.commands.gang.user: true
      
# ALL Admin Claim Permissions #
  mychunk.claim.*:
    description: Can claim chunks for self/server/others
    children:
       mychunk.claim: true
       mychunk.claim.others: true
       mychunk.claim.server: true
       mychunk.claim.public: true
       mychunk.claim.unlimited: true
       mychunk.claim.others.unlimited: true
       mychunk.claim.overbuy: true
       mychunk.claim.area: true

# ALL Unclaim Permissions #
  mychunk.unclaim.*:
    description: Can unclaim chunks for others/server
    children:
      mychunk.unclaim.others: true
      mychunk.unclaim.server: true
      mychunk.unclaim.public: true

# ALL Server Chunk Permissions #
  mychunk.server.*:
    description: Can build/destroy/use in server owned chunks.
    children:
      mychunk.server.animals: true
      mychunk.server.build: true
      mychunk.server.chests: true
      mychunk.server.destroy: true
      mychunk.server.doors: true
      mychunk.server.entry: true
      mychunk.server.ignite: true
      mychunk.server.lava: true
      mychunk.server.use: true
      mychunk.server.special: true
      mychunk.server.signs: true
      mychunk.server.water: true
      
# ALL Public Chunk Permissions #
  mychunk.public.*:
    description: Has all public permissions
    default: true
    children:
      mychunk.public.build: true
      mychunk.public.chests: true
      mychunk.public.destroy: true
      mychunk.public.doors: true
      mychunk.public.ignite: true
      mychunk.public.lava: true
      mychunk.public.use: true
      mychunk.public.special: true
      mychunk.public.signs: true
      mychunk.public.water: true

# Default User Permissions #
# NOTE: Overbuy Not Included #
  mychunk.user:
    description: Access to all permissions an average user would need
    children:
      mychunk.claim: true
      mychunk.buy: true
      mychunk.sell: true
      mychunk.allowmobs: true
      mychunk.allowpvp: true
      mychunk.lease: true
      mychunk.commands.user: true
      mychunk.gang.user: true

# Gang User Permission #
  mychunk.gang.user:
    description: Access to all default gang user permissions
    children:
      mychunk.commands.gang.user: true

# Default User Commands #
  mychunk.commands.user:
    description: Access to all commands a normal user would need
    children:
      mychunk.commands.allow: true
      mychunk.commands.allowmobs: true
      mychunk.commands.allowpvp: true
      mychunk.commands.claim: true
      mychunk.commands.disallow: true
      mychunk.commands.flags: true
      mychunk.commands.forsale: true
      mychunk.commands.help: true
      mychunk.commands.info: true
      mychunk.commands.notforsale: true
      mychunk.commands.owner: true
      mychunk.commands.stats: true
      mychunk.commands.unclaim: true
      mychunk.commands.gang.user: true
      
# Default Gang User Commands #
  mychunk.commands.gang.user:
    description: Acecss to all gang commands a normal user would need
    children:
      mychunk.commands.gang.claim: true
      mychunk.commands.gang.create: true
      mychunk.commands.gang.disband: true
      mychunk.commands.gang.join: true
      mychunk.commands.gang.leave: true
      mychunk.commands.gang.status: true
      mychunk.commands.gang.toggle.*: true
      mychunk.commands.gang.unclaim: true
      mychunk.commands.gang.help: true

##########################
# Individual Permissions #
##########################

# General Permissions #
  
  mychunk.free:
    description: Player does not pay to claim chunks
  
  mychunk.override:
    description: Player can bypass chunk protections (handle with care!)
  
  mychunk.sell:
    description: Can sell chunks with a [For Sale] sign
    
  mychunk.buy:
    description: Can buy chunks set as [For Sale]
  
  mychunk.allowmobs:
    description: Can use [AllowMobs] signs
    
  mychunk.allowpvp:
    description: Can use [AllowPVP] signs
  
  mychunk.lease:
    description: Can use [Lease] signs

# Commands #

  mychunk.commands.stats:
    description: Access to command /mychunk
  
  mychunk.commands.help:
    description: Access to command /mychunk help
    
  mychunk.commands.info:
    description: Access to command /mychunk info {page}
    
  mychunk.commands.info.others:
    description: Access to command /mychunk info [player] {page}
    
  mychunk.commands.claim:
    description: Access to command /mychunk claim
    
  mychunk.commands.claimarea:
    description: Access to command /mychunk claimarea
  
  mychunk.commands.unclaim:
    description: Access to command /mychunk unclaim
  
  mychunk.commands.unclaimarea:
    description: Access to command /mychunk unclaimarea
  
  mychunk.commands.owner:
    description: Access to command /mychunk owner
    
  mychunk.commands.allow:
    description: Access to command /mychunk allow
  
  mychunk.commands.disallow:
    description: Access to command /mychunk disallow
    
  mychunk.commands.flags:
    description: Access to command /mychunk flags
    
  mychunk.commands.allowmobs:
    description: Access to command /mychunk allowmobs
    
  mychunk.commands.allowpvp:
    description: Access to command /mychunk allowpvp

  mychunk.commands.price:
    description: Access to command /mychunk price
    
  mychunk.commands.obprice:
    description: Access to command /mychunk obprice
    
  mychunk.commands.max:
    description: Access to command /mychunk max
    
  mychunk.commands.ramprate:
    description: Access to command /mychunk ramprate
    
  mychunk.commands.expirydays:
    description: Access to command /mychunk expirydays
    
  mychunk.commands.gangnamelength:
    description: Access to command /mychunk gangnamelength

  mychunk.commands.refund:
    description: Access to command /mychunk refund
    
  mychunk.commands.reload:
    description: Access to /mychunk reload

  mychunk.commands.purge.*:
    description: Access to all /muchunk purgep and /mychunk purgew
    children:
      mychunk.commands.purgep: true
      mychunk.commands.purgew: true  
  
  mychunk.commands.purgep:
    description: Access to /mychunk purgep
    
  mychunk.commands.purgew:
    description: Access to /mychunk purgew

  mychunk.commands.toggle.*:
    description: Access to all commands starting with /mychunk toggle
    children:
      mychunk.commands.toggle.refund: true
      mychunk.commands.toggle.overbuy: true
      mychunk.commands.toggle.resales: true
      mychunk.commands.toggle.neighbours: true
      mychunk.commands.toggle.unclaimed: true
      mychunk.commands.toggle.tnt: true
      mychunk.commands.toggle.expiry: true
      mychunk.commands.toggle.allownether: true
      mychunk.commands.toggle.allowend: true
      mychunk.commands.toggle.notify: true
      mychunk.commands.toggle.firstChunkFree: true
      mychunk.commands.toggle.preventEntry: true
      mychunk.commands.toggle.preventPVP: true
      mychunk.commands.toggle.mobGrief: true
      mychunk.commands.toggle.rampchunkprice: true
      mychunk.commands.toggle.usechatformat: true
    
  mychunk.commands.toggle.refund:
    description: Access to command /mychunk toggle refund
    
  mychunk.commands.toggle.overbuy:
    description: Access to command /mychunk toggle overbuy
    
  mychunk.commands.toggle.resales:
    description: Access to command /mychunk toggle resales
    
  mychunk.commands.toggle.neighbours:
    description: Access to command /mychunk toggle neighbours
    
  mychunk.commands.toggle.unclaimed:
    description: Access to command /mychunk toggle unclaimed
    
  mychunk.commands.toggle.tnt:
    description: Access to command /mychunk toggle tnt
    
  mychunk.commands.toggle.expiry:
    description: Access to command /mychunk toggle expiry
    
  mychunk.commands.toggle.allownether:
    description: Access to command /mychunk toggle allownether
    
  mychunk.commands.toggle.allowend:
    description: Access to command /mychunk toggle allowend
    
  mychunk.commands.toggle.notify:
    description: Access to command /mychunk toggle notify
    
  mychunk.commands.toggle.firstChunkFree:
    description: Access to command /mychunk toggle firstChunkFree
    
  mychunk.commands.toggle.preventEntry:
    description: Access to command /mychunk toggle preventEntry
    
  mychunk.commands.toggle.preventPVP:
    description: Access to command /mychunk toggle preventPVP
    
  mychunk.commands.toggle.mobGrief:
    description: Access to command /mychunk toggle mobGrief
    
  mychunk.commands.toggle.rampchunkprice:
    description: Access to command /mychunk toggle rampchunkprice
  
  mychunk.commands.toggle.usechatformat:
    description: Access to command /mychunk toggle usechatformat
      
  mychunk.commands.world.*:
    description: Access to /mychunk world ...
    children:
      mychunk.commands.world.list: true
      mychunk.commands.world.enable: true
      mychunk.commands.world.disable: true
      mychunk.commands.world.enable.all: true
      mychunk.commands.world.disable.all: true
      
  mychunk.commands.world.list:
    description: Access to /mychunk world list

  mychunk.commands.world.enable:
    description: Access to /mychunk world enable
    
  mychunk.commands.world.disable:
    description: Access to /mychunk world disable
    
  mychunk.commands.world.enable.all:
    description: Access to /mychunk world enable all
    
  mychunk.commands.world.disable.all:
    description: Access to /mychunk world disable all

# Claim Permissions #

  mychunk.claim:
    description: Can claim chunks
    
  mychunk.claim.unlimited:
    description: Can ignore max chunk limit when claiming for self
    
  mychunk.claim.others:
    description: Can claim chunks for other players
    
  mychunk.claim.others.unlimited:
    description: Can ignore max chunk limit when claiming for others
    
  mychunk.claim.server:
    description: Can claim chunks for the server
    
  mychunk.claim.public:
    description: Can claim chunks public chunks
    
  mychunk.claim.overbuy:
    description: Can buy more than the max limit for the overbuy price
    
  mychunk.claim.area:
    description: Can buy chunks usign [ClaimArea] signs
    
# Unclaim Permissions #

  mychunk.unclaim.others:
    description: Can unclaim chunks for other players
    
  mychunk.unclaim.server:
    description: Can unclaim chunks for the server
    
  mychunk.unclaim.public:
    description: Can unclaim public chunks

# Server Chunk Permissions #

  mychunk.server.animals:
    description: Can interact with/kill animals in server chunks
  
  mychunk.server.build:
    description: Can build in server owned chunks
    
  mychunk.server.chests:
    description: Can open chests in server owned chunks
    
  mychunk.server.destroy:
    description: Can destroy blocks in server owned chunks
    
  mychunk.server.doors:
    description: Can open doors in server owned chunks
    
  mychunk.server.entry:
    description: Can enter server owned chunks
    
  mychunk.server.ignite:
    description: Can use explosives and Flint & Steel in server owned chunks
    
  mychunk.server.lava:
    description: Can empty lava uckets in Server owned chunks
    
  mychunk.server.use:
    description: Can use levers, buttons etc in Server owned chunks
    
  mychunk.server.special:
    description: Can access furnaces, dispensers and brewing stands in Server owned chunks
    
  mychunk.server.signs:
    description: Can use [Allow], [For Sale] etc in Server owned chunks
    
  mychunk.server.water:
    description: Can empty water buckets in Server owned chunks

# Public Chunk Permissions #

  mychunk.public.build:
    description: Can build in public chunks
    
  mychunk.public.chests:
    description: Can open chests in public chunks
    
  mychunk.public.destroy:
    description: Can destroy blocks in public chunks
    
  mychunk.public.doors:
    description: Can open doors in public chunks
    
  mychunk.public.ignite:
    description: Can use explosives and Flint & Steel in public chunks
    
  mychunk.public.lava:
    description: Can empty lava uckets in public chunks
    
  mychunk.public.use:
    description: Can use levers, buttons etc in public chunks
    
  mychunk.public.special:
    description: Can access furnaces, dispensers and brewing stands in public chunks
    
  mychunk.public.signs:
    description: Can use [Allow], [For Sale] etc in public chunks
    
  mychunk.public.water:
    description: Can empty water buckets in public chunks

#########################
# GANGLANDS PERMISSIONS #
#########################

# GANGLANDS COMMANDS #

mychunk.commands.gang.create:
  description: Access to /gang create
  
mychunk.commands.gang.disband:
  description: Access to /gang disband
  
mychunk.commands.gang.join:
  description: Access to /gang join
  
mychunk.commands.gang.leave:
  description: Access to /gang leave
  
mychunk.commands.gang.status:
  description: Access to /gang

mychunk.commands.gang.toggle.*:
  description: Access to all /gang toggle commands
  children:
    mychunk.commands.gang.toggle.public: true
  
mychunk.commands.gang.toggle.public:
  desciption: Access to /gang toggle public