name: MyChunk
main: me.ellbristow.mychunk.MyChunk
version: 0.2.1
author: ellbristow
description: >
             Buy/Sell chunks for currency, get protection, make profit.
softdepend: [Vault,My Worlds,Multiverse]

commands:
  mychunk:
    description: Main (and only) command

permissions:

# Admin Permissions
  mychunk.*:
    description: Admin permission for total access
    default: op
    children:
      mychunk.commands.*: true
      mychunk.claim.*: true
      mychunk.free: true
      mychunk.override: true
      mychunk.server.*: true
      mychunk.unclaim.*: true
  
  mychunk.free:
    description: Player does not pay to claim chunks
    default: op
  
  mychunk.override:
    description: Player can bypass chunk protections (handle with care!)
    default: op

# Command Permissions
  mychunk.commands.*:
    description: Access to all MyChunk commands
    default: op
    children:
      mychunk.commands.stats: true
      mychunk.commands.price: true
      mychunk.commands.max: true
      mychunk.commands.flags: true
  mychunk.commands.price:
    description: Access to command /mychunk price
    default: op
  mychunk.commands.max:
    description: Access to command /mychunk max
    default: op
  mychunk.commands.stats:
    description: Access to command /mychunk
    default: op
  mychunk.commands.flags:
    description: Access to command /mychunk flags
    default: op
  mychunk.commands.toggle.*:
    description: Access to all commands starting with /mychunk toggle
    default: op
    children:
      mychunk.commands.toggle.refund: true
  mychunk.commands.toggle.refund:
    description: Access to command /mychunk toggle refund
    default: op

# Claim Permissions
  mychunk.claim.*:
    description: Can claim chunks for self/server/others
    default: op
    children:
       mychunk.claim: true
       mychunk.claim.others: true
       mychunk.claim.server: true
       mychunk.claim.unlimited: true
       mychunk.claim.others.unlimited: true
  mychunk.claim:
    description: Can claim chunks
    default: op
  mychunk.claim.unlimited:
    description: Can ignore max chunk limit when claiming for self
    default: op
  mychunk.claim.others:
    description: Can claim chunks for other players
    default: op
  mychunk.claim.others.unlimited:
    description: Can ignore max chunk limit when claiming for others
    default: op
  mychunk.claim.server:
    description: Can claim chunks for the server
    default: op

# Server Permissions
  mychunk.server.*:
    description: Can build/destroy/use in server owned chunks.
    default: false
    children:
      mychunk.server.build: true
      mychunk.server.chests: true
      mychunk.server.destroy: true
      mychunk.server.doors: true
      mychunk.server.ignite: true
      mychunk.server.use: true
  mychunk.server.build:
    description: Can build in server owned chunks
    default: op
  mychunk.server.chests:
    description: Can open chests in server owned chunks
    default: op
  mychunk.server.destroy:
    description: Can destroy blocks in server owned chunks
    default: op
  mychunk.server.doors:
    description: Can open doors in server owned chunks
    default: op
  mychunk.server.ignite:
    description: Can use explosives and Flint & Steel in server owned chunks
    default: op
  mychunk.server.use:
    description: Can use levers, buttons etc in server owned chunks
    default: op

# Unclaim Permissions
  mychunk.unclaim.*:
    description: Can unclaim chunks for others/server
    default: op
    children:
      mychunk.unclaim.others: true
      mychunk.unclaim.server: true
  mychunk.unclaim.others:
    description: Can unclaim chunks for other players
    default: op
  mychunk.unclaim.server:
    description: Can unclaim chunks for other players
    default: op